name: build-app-and-test

on:
  push:
    branches: test_branch

  workflow_dispatch:

jobs:
  build_application:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v4

      - name: give permission to build app bash
        run: chmod +x ci/build-app.sh

      - name: log progress1
        run: echo executing command in file ci/build-app.sh

      - name: build app
        run: ci/build-app.sh

      - name: log progress2
        run: echo execution passed

      - name: give permission to unit test bash
        run: chmod +x ci/unit-test-app.sh

      - name: log progress3
        run: echo Getting ready to run the tests!

      - name: run tests
        run: ci/unit-test-app.sh

      - name: log progress4
        run: echo finished running tests
