name: create-docker-image

on:
  push:
    branches: test_branch

  workflow_dispatch:

env:
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  build_and_store:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v4

      - name: give permission to build app bash
        run: chmod +x ci/build-app.sh

      - name: build app
        run: ci/build-app.sh

      - name: give permission to unit test bash
        run: chmod +x ci/unit-test-app.sh

      - name: run tests
        run: ci/unit-test-app.sh

      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .

  linting:
    runs-on: ubuntu-latest
    needs: [build_and_store]
    steps: 
      - name: download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true 

  docker_image:
   runs-on: ubuntu-latest
   needs: [build_and_store]
   permissions: 
     packages: write

   steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: ghcr.io/${{ github.actor }}/micronaut-app:1.0-${{ github.sha }},ghcr.io/${{ github.actor }}/micronaut-app:latest

