name: build_with_matrix

on:
  push:
    branches: test_branch

  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:

      - name: clone down
        uses: actions/checkout@v4

      - run: chmod +x ci/build-app.sh

      - name: Build
        run: ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh
